[package]
name = "helium"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "mod"
harness = false
